pub const GitError = error{
    GIT_EINVALID,
    GIT_EINVALIDSPEC,
    GIT_ENOTFOUND,
    GIT_EAMBIGUOUS,
    LIBGIT2_NOT_INITIALIZED,
    LIBGIT2_NOT_SHUTDOWN,
    REPOSITORY_NOT_OPEN,
    REPOSITORY_CORRUPTED,
    REPOSITORY_STATE_CLEANUP,
    UNEXPECTED_ERROR,
    // Note-specific errors
    NOTE_CREATE_FAILED,
    NOTE_READ_FAILED,
    NOTE_UPDATE_FAILED,
    NOTE_DELETE_FAILED,
    NOTE_ITERATOR_FAILED,
    NOTE_MALFORMED_CONTENT,
    // Signature-specific errors
    SIGNATURE_DEFAULT_FAILED,
    SIGNATURE_CREATE_FAILED,
};
