pub const GitError = error{
    GIT_EINVALIDSPEC,
    GIT_ENOTFOUND,
    LIBGIT2_NOT_INITIALIZED,
    LIBGIT2_NOT_SHUTDOWN,
    REPOSITORY_NOT_OPEN,
    REPOSITORY_CORRUPTED,
    REPOSITORY_STATE_CLEANUP,
    UNEXPECTED_ERROR,
};
